---
swagger: "2.0"
info:
  description: "No description"
  version: "1.0.0"
  title: "API Carrinho"
  contact: {}
host: localhost:8080
basePath: /rest/carrinho
schemes: 
    - http
    - https
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /listarcarrinhos:
    get:
      summary: "Listar Carrinhos"
      description: "Metodo de listar todos os carrinhos disponiveis"
      parameters: []
      responses:
        200:
          description: "Retorna os carrinhos criados"
        204:
          description: "Caso não exista nenhum carrinho criado"
definitions:
  ProdutoDTO:
    type: "object"
    required:
    - "codigo"
    - "descricao"
    properties:
      codigo:
        type: "number"
        description: "codigo do produto"
      descricao:
        type: "string"
        description: "descricao do produto"
  ItemDTO:
    type: "object"
    required:
    - "produto"
    properties:
      produto:
        $ref: "#/definitions/ProdutoDTO"
      valorUnitario:
        type: "number"
        description: "valor unitario do produto"
      quantidade:
        type: "number"
        description: "quantidade add no carrinho"
  UsuarioDTO:
    type: "object"
    required:
    - "cpf"
    properties:
      cpf:
        type: "string"
